### ISSUE TITLE
I like the idea! But how do I run it?

### ISSUE THREAD

**Issue by SebSaga** [graemeniedermayer/clothseg#1]
I installed via URL, not sure what to do next :)

**Comment by graemeniedermayer** [comment]
I updated the readme to add some examples. On the txt2img or img2img tab you should be able to set the `script` to "remove_bg v0.0.2" (I might change the name to clothing_seg for consistency). That should add extra images to the auto1111 output that have the background remove or the clothing split into 3 categories (top, bottom, and combined) depending on the model.

If you pick the masking option, they'll output white masks that you can use with inpainting.

Hopefully that helps! let me know you're still having difficulties.
