### ISSUE TITLE
TypeError: _argmax_dispatcher() got an unexpected keyword argument 'keepdims'

### ISSUE THREAD

**Issue by maelfonrei** [graemeniedermayer/clothseg#2]
```
Error completing request
Arguments: ('task(nc1hvqo5kce170y)', 0, '', '', [], <PIL.Image.Image image mode=RGBA size=1440x1800 at 0x7F60747EB7F0>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 0, -1.0, -1.0, 0, 0, 0, False, 512, 512, 1, 0, 32, 0, '', '', '', [], 9, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 'u2net_cloth_seg', True, True, True, True) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/img2img.py", line 166, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/clothseg/scripts/remove_bg.py", line 83, in run
    remove_img = remove(processed.images[count], session=session)
  File "/usr/local/lib/python3.8/dist-packages/rembg/bg.py", line 135, in remove
    masks = session.predict(img)
  File "/usr/local/lib/python3.8/dist-packages/rembg/session_cloth.py", line 64, in predict
    pred = np.argmax(pred, axis=1, keepdims=True)
  File "<__array_function__ internals>", line 4, in argmax
TypeError: _argmax_dispatcher() got an unexpected keyword argument 'keepdims'
```

This problem is only with u2net_cloth_seg. Other models work fine.

Maybe I'm just doing something wrong?
I go into img2img and select the image, then in Script I select remove_bg v0.0.2 and run.

Denoising strength to 0 (I don't want the image to change).

**Comment by graemeniedermayer** [comment]
Do you get the same issue for batched images and txt2img?

I haven't updated automatic1111 recently so I'll check if any updates broke anything tonight.

**Comment by maelfonrei** [comment]
Same error in text2img (all but u2net_cloth_seg work fine).
I haven't tried using batch.

Tried jpeg and png with resolutions from 1440x1800 to 512x512 - same error.

**Comment by graemeniedermayer** [comment]
Hmm this error is a little vague, np.argmax definitely has keepdims so the error about `pred = np.argmax(pred, axis=1, keepdims=True)` probably means that the inside `pred` is probably not actually the numpy matrix it should be.

There could be an issue with that specific model `models/rem_bg/u2net_human_seg.onnx` if you delete it it should redownload (it should be about 176mb if it's less maybe the download got interrupted)

**Comment by graemeniedermayer** [comment]
That's really interesting, that there's only u2net_cloth_seg.onnx. If you managed to get the background removal working there should be `u2net.onnx` or `u2net_human_seg.onnx` as well.

So this might be a pathing issue.

The fallback should be `~/.u2net/` although you might want to just search for it. If you do find the u2net.onnx working in a different location maybe move u2net_cloth_seg.onnx there? Although I'm still confused why the pathing would be different for `u2net_cloth_seg.onnx`.

**Comment by maelfonrei** [comment]
Other files appear there, it's just that after reinstalling, I only ran `u2net_cloth_seg.onnx`.

It's a pity that it doesn't work for me.

**Comment by graemeniedermayer** [comment]
Oh I found someone who had the same problem with the underlying library! https://github.com/danielgatis/rembg/issues/302

It seems like there was a very particular version of numpy that didn't have `keepdims`. So the version of numpy used is probably incompatible with rembg.

Upgrading numpy might work `pip install numpy --upgrade` or using conda. Although you might want to check your numpy version after running auto1111 because often packages get downgraded during runtime for compatibility reasons.

**Comment by maelfonrei** [comment]
Thank you, it all works now.
